### ISSUE TITLE
v1.0.21 messages: [MySQL] 2016/10/14 10:31:13 statement.go:27: Invalid Connection 

### ISSUE THREAD

**Issue by mizioumt** [github/gh-ost#271] opened 2016-10-14 15:02 UTC
`gh-ost with --test-on-replica`, 100M rows, the run finished successfully, haven't checked the data yet.
There were a few strange messages in the log,
should I or yourself worry about these?

```
grep Connect gh-ost.log
[MySQL] 2016/10/14 10:31:13 statement.go:27: Invalid Connection
[MySQL] 2016/10/14 11:27:24 statement.go:27: Invalid Connection
[MySQL] 2016/10/14 12:18:01 statement.go:27: Invalid Connection
[MySQL] 2016/10/14 13:00:01 statement.go:27: Invalid Connection
[MySQL] 2016/10/14 13:48:53 statement.go:27: Invalid Connection
```

**Comment by shlomi-noach** [comment] 2016-10-14 15:10
Pro tip: use three backticks to enclose multi-line code. See how I edited your comment.

**Comment by shlomi-noach** [comment] 2016-10-14 15:11
Duplicate of https://github.com/github/gh-ost/issues/207

**Closed** 2016-10-14 15:11 UTC
Labels: duplicate
