### ISSUE TITLE
Hang in `throttled` state

### ISSUE THREAD

**Issue by NearTan** [github/gh-ost#505] opened 2017-10-23 04:48 UTC
I create MariaDB(version 10.1.28) master-slave instances by Docker container, when I run command 
```
./gh-ost \
--port=33092 \
--user="root" \
--database="ghost" \
--table="test_2" \
--alter="engine=innodb" \
--initially-drop-ghost-table \
--max-load=Threads_running=25 \
--critical-load=Threads_running=1000 \
--debug \
--execute
```

it seems hang in `throttled` state
```
2017-10-23 12:11:07 INFO starting gh-ost 1.0.42
2017-10-23 12:11:07 INFO Migrating `ghost`.`test_2`
2017-10-23 12:11:07 INFO connection validated on 127.0.0.1:33092
2017-10-23 12:11:07 INFO User has ALL privileges
2017-10-23 12:11:07 INFO binary logs validated on 127.0.0.1:33092
2017-10-23 12:11:07 INFO Restarting replication on 127.0.0.1:33092 to make sure binlog settings apply to replication thread
2017-10-23 12:11:07 DEBUG Replication restarted
2017-10-23 12:11:07 INFO Inspector initiated on eb154ec93e94:33092, version 10.1.28-MariaDB
2017-10-23 12:11:07 INFO Table found. Engine=InnoDB
2017-10-23 12:11:07 DEBUG Estimated number of rows via STATUS: 784080
2017-10-23 12:11:07 DEBUG Validated no foreign keys exist on table
2017-10-23 12:11:07 DEBUG Validated no triggers exist on table
2017-10-23 12:11:07 INFO Estimated number of rows via EXPLAIN: 784080
2017-10-23 12:11:07 DEBUG Potential unique keys in test_2: [PRIMARY (auto_increment): [id]; has nullable: false]
2017-10-23 12:11:07 INFO Recursively searching for replication master
2017-10-23 12:11:07 DEBUG Looking for master on 127.0.0.1:33092
2017-10-23 12:11:07 DEBUG Master of 127.0.0.1:33092 is master:33091
2017-10-23 12:11:07 DEBUG Looking for master on master:33091
2017-10-23 12:11:07 INFO Master found to be master:33091
2017-10-23 12:11:07 INFO log_slave_updates validated on 127.0.0.1:33092
2017-10-23 12:11:07 INFO connection validated on 127.0.0.1:33092
2017-10-23 12:11:07 DEBUG Streamer binlog coordinates: mysql-bin.000002:37435135
2017/10/23 12:11:07 binlogsyncer.go:75: [info] create BinlogSyncer with config &{99999 mysql 127.0.0.1 33092 root   false false <nil>}
2017-10-23 12:11:07 INFO Connecting binlog streamer at mysql-bin.000002:37435135
2017/10/23 12:11:07 binlogsyncer.go:241: [info] begin to sync binlog from position (mysql-bin.000002, 37435135)
2017/10/23 12:11:07 binlogsyncer.go:134: [info] register slave for master server 127.0.0.1:33092
2017-10-23 12:11:07 DEBUG Beginning streaming
2017/10/23 12:11:07 binlogsyncer.go:568: [info] rotate to (mysql-bin.000002, 37435135)
2017-10-23 12:11:07 INFO rotate to next log name: mysql-bin.000002
2017-10-23 12:11:07 INFO connection validated on master:33091
2017-10-23 12:11:07 INFO connection validated on master:33091
2017-10-23 12:11:07 INFO will use time_zone='SYSTEM' on applier
2017-10-23 12:11:07 INFO Examining table structure on applier
2017-10-23 12:11:07 INFO Applier initiated on 64716996105b:33091, version 10.1.28-MariaDB
2017-10-23 12:11:07 INFO Droppping table `ghost`.`_test_2_gho`
2017-10-23 12:11:07 INFO Table dropped
2017-10-23 12:11:07 INFO Droppping table `ghost`.`_test_2_ghc`
2017-10-23 12:11:08 INFO Table dropped
2017-10-23 12:11:08 INFO Creating changelog table `ghost`.`_test_2_ghc`
2017-10-23 12:11:08 INFO Changelog table created
2017-10-23 12:11:08 INFO Creating ghost table `ghost`.`_test_2_gho`
2017-10-23 12:11:08 INFO Ghost table created
2017-10-23 12:11:08 INFO Altering ghost table `ghost`.`_test_2_gho`
2017-10-23 12:11:08 DEBUG ALTER statement: alter /* gh-ost */ table `ghost`.`_test_2_gho` engine=innodb
2017-10-23 12:11:09 INFO Ghost table altered
2017-10-23 12:11:09 INFO Waiting for ghost table to be migrated. Current lag is 0s
2017-10-23 12:11:09 INFO Intercepted changelog state GhostTableMigrated
2017-10-23 12:11:09 INFO Handled changelog state GhostTableMigrated
2017-10-23 12:11:09 DEBUG ghost table migrated
2017-10-23 12:11:09 DEBUG Potential unique keys in _test_2_gho: [PRIMARY (auto_increment): [id]; has nullable: false]
2017-10-23 12:11:09 INFO Chosen shared unique key is PRIMARY
2017-10-23 12:11:09 INFO Shared columns are id,key,key1,key2,update_time
2017-10-23 12:11:09 INFO Listening on unix socket file: /tmp/gh-ost.ghost.test_2.sock
2017-10-23 12:11:09 DEBUG Reading migration range according to key: PRIMARY
2017-10-23 12:11:09 INFO Migration min values: [23752]
2017-10-23 12:11:09 DEBUG Reading migration range according to key: PRIMARY
2017-10-23 12:11:09 INFO Migration max values: [6669079]
2017-10-23 12:11:09 INFO Waiting for first throttle metrics to be collected
2017-10-23 12:11:09 ERROR parsing time "" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "2006"
2017-10-23 12:11:09 INFO First throttle metrics collected
2017-10-23 12:11:09 DEBUG Operating until row copy is complete
2017-10-23 12:11:09 DEBUG Getting nothing in the write queue. Sleeping...
# Migrating `ghost`.`test_2`; Ghost table is `ghost`.`_test_2_gho`
# Migrating 64716996105b:33091; inspecting eb154ec93e94:33092; executing on nears-MacBook-Pro.local
# Migration started at Mon Oct 23 12:11:07 +0800 2017
# chunk-size: 1000; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: Threads_running=25; critical-load: Threads_running=1000; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# Serving on unix socket: /tmp/gh-ost.ghost.test_2.sock
Copy: 0/784080 0.0%; Applied: 0; Backlog: 0/1000; Time: 2s(total), 0s(copy); streamer: mysql-bin.000002:37436417; State: migrating; ETA: N/A
2017-10-23 12:11:09 ERROR parsing time "" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "2006"
2017-10-23 12:11:10 DEBUG Issued INSERT on range: [23752]..[24751]; iteration: 0; chunk-size: 1000
Copy: 0/784080 0.0%; Applied: 0; Backlog: 0/1000; Time: 3s(total), 1s(copy); streamer: mysql-bin.000002:37440129; State: migrating; ETA: N/A
2017-10-23 12:11:10 DEBUG Issued INSERT on range: [24751]..[25751]; iteration: 1; chunk-size: 1000
2017-10-23 12:11:11 DEBUG Issued INSERT on range: [25751]..[26751]; iteration: 2; chunk-size: 1000
2017-10-23 12:11:11 DEBUG Issued INSERT on range: [26751]..[27751]; iteration: 3; chunk-size: 1000
2017-10-23 12:11:11 DEBUG Issued INSERT on range: [27751]..[28751]; iteration: 4; chunk-size: 1000
2017-10-23 12:11:11 DEBUG Issued INSERT on range: [28751]..[29751]; iteration: 5; chunk-size: 1000
Copy: 6000/784080 0.8%; Applied: 0; Backlog: 0/1000; Time: 4s(total), 2s(copy); streamer: mysql-bin.000002:37510090; State: migrating; ETA: N/A
2017-10-23 12:11:11 DEBUG Issued INSERT on range: [29751]..[30751]; iteration: 6; chunk-size: 1000
2017-10-23 12:11:11 DEBUG Issued INSERT on range: [30751]..[31751]; iteration: 7; chunk-size: 1000
2017-10-23 12:11:12 DEBUG Issued INSERT on range: [31751]..[32751]; iteration: 8; chunk-size: 1000
2017-10-23 12:11:12 DEBUG Issued INSERT on range: [32751]..[33751]; iteration: 9; chunk-size: 1000
2017-10-23 12:11:12 DEBUG Issued INSERT on range: [33751]..[34751]; iteration: 10; chunk-size: 1000
Copy: 11000/784080 1.4%; Applied: 0; Backlog: 0/1000; Time: 5s(total), 3s(copy); streamer: mysql-bin.000002:37557222; State: migrating; ETA: 3m36s
2017-10-23 12:11:12 DEBUG Issued INSERT on range: [34751]..[35751]; iteration: 11; chunk-size: 1000
2017-10-23 12:11:13 DEBUG Issued INSERT on range: [35751]..[36751]; iteration: 12; chunk-size: 1000
Copy: 13000/784080 1.7%; Applied: 0; Backlog: 0/1000; Time: 6s(total), 4s(copy); streamer: mysql-bin.000002:37603892; State: throttled, lag=1.501912s; ETA: 4m2s
2017-10-23 12:11:13 DEBUG Issued INSERT on range: [36751]..[37751]; iteration: 13; chunk-size: 1000
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 7s(total), 5s(copy); streamer: mysql-bin.000002:37650488; State: throttled, lag=2.203634s; ETA: 4m39s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 8s(total), 6s(copy); streamer: mysql-bin.000002:37720458; State: throttled, lag=2.713891s; ETA: 5m35s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 9s(total), 7s(copy); streamer: mysql-bin.000002:37745013; State: throttled, lag=3.186269s; ETA: 6m29s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 10s(total), 8s(copy); streamer: mysql-bin.000002:37768962; State: throttled, lag=3.643499s; ETA: 7m25s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 11s(total), 9s(copy); streamer: mysql-bin.000002:37771411; State: throttled, lag=4.031085s; ETA: 8m19s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 12s(total), 10s(copy); streamer: mysql-bin.000002:37774203; State: throttled, lag=4.471950s; ETA: 9m14s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 13s(total), 11s(copy); streamer: mysql-bin.000002:37777092; State: throttled, lag=4.898709s; ETA: 10m9s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 14s(total), 12s(copy); streamer: mysql-bin.000002:37780156; State: throttled, lag=5.165900s; ETA: 11m4s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 15s(total), 13s(copy); streamer: mysql-bin.000002:37782203; State: throttled, lag=5.652501s; ETA: 11m59s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 16s(total), 14s(copy); streamer: mysql-bin.000002:37784156; State: throttled, lag=6.267008s; ETA: 12m54s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 17s(total), 15s(copy); streamer: mysql-bin.000002:37787448; State: throttled, lag=6.741759s; ETA: 13m49s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 18s(total), 16s(copy); streamer: mysql-bin.000002:37789839; State: throttled, lag=7.160522s; ETA: 14m44s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 19s(total), 17s(copy); streamer: mysql-bin.000002:37792919; State: throttled, lag=7.602088s; ETA: 15m39s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 20s(total), 18s(copy); streamer: mysql-bin.000002:37795354; State: throttled, lag=7.905196s; ETA: 16m35s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 21s(total), 19s(copy); streamer: mysql-bin.000002:37798435; State: throttled, lag=8.302424s; ETA: 17m30s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 22s(total), 20s(copy); streamer: mysql-bin.000002:37801288; State: throttled, lag=8.801842s; ETA: 18m24s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 23s(total), 21s(copy); streamer: mysql-bin.000002:37803455; State: throttled, lag=9.203401s; ETA: 19m20s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 24s(total), 22s(copy); streamer: mysql-bin.000002:37806038; State: throttled, lag=9.892248s; ETA: 20m15s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 25s(total), 23s(copy); streamer: mysql-bin.000002:37808699; State: throttled, lag=10.064135s; ETA: 21m10s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 26s(total), 24s(copy); streamer: mysql-bin.000002:37811070; State: throttled, lag=10.352151s; ETA: 22m4s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 27s(total), 25s(copy); streamer: mysql-bin.000002:37814306; State: throttled, lag=10.771618s; ETA: 22m59s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 28s(total), 26s(copy); streamer: mysql-bin.000002:37817022; State: throttled, lag=11.173454s; ETA: 23m54s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 29s(total), 27s(copy); streamer: mysql-bin.000002:37818708; State: throttled, lag=11.598983s; ETA: 24m50s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 30s(total), 28s(copy); streamer: mysql-bin.000002:37820047; State: throttled, lag=12.501022s; ETA: 25m44s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 31s(total), 29s(copy); streamer: mysql-bin.000002:37821237; State: throttled, lag=13.142864s; ETA: 26m40s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 32s(total), 30s(copy); streamer: mysql-bin.000002:37822442; State: throttled, lag=13.382003s; ETA: 27m34s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 33s(total), 31s(copy); streamer: mysql-bin.000002:37824264; State: throttled, lag=14.573279s; ETA: 28m30s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 34s(total), 32s(copy); streamer: mysql-bin.000002:37826005; State: throttled, lag=14.999559s; ETA: 29m24s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 35s(total), 33s(copy); streamer: mysql-bin.000002:37827195; State: throttled, lag=15.901134s; ETA: 30m20s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 36s(total), 34s(copy); streamer: mysql-bin.000002:37828400; State: throttled, lag=16.197906s; ETA: 31m15s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 37s(total), 35s(copy); streamer: mysql-bin.000002:37829741; State: throttled, lag=17.443810s; ETA: 32m10s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 38s(total), 36s(copy); streamer: mysql-bin.000002:37830986; State: throttled, lag=17.932967s; ETA: 33m5s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 39s(total), 37s(copy); streamer: mysql-bin.000002:37832176; State: throttled, lag=18.673887s; ETA: 34m0s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 40s(total), 38s(copy); streamer: mysql-bin.000002:37833517; State: throttled, lag=19.799566s; ETA: 34m54s
Copy: 14000/784080 1.8%; Applied: 0; Backlog: 0/1000; Time: 41s(total), 39s(copy); streamer: mysql-bin.000002:37834762; State: throttled, lag=20.298345s; ETA: 35m50s
^C
```

table schema of `test_2` 
```
CREATE TABLE `test_2` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `key` mediumtext CHARACTER SET ucs2,
  `key1` int(11) NOT NULL,
  `key2` varchar(128) CHARACTER SET ucs2 DEFAULT '0',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6669080 DEFAULT CHARSET=utf8
```
I recur this issue both release `1.0.42` and build by myself with go1.8.3 in macOS 10.13.

**Comment by shlomi-noach** [comment] 2017-10-23 05:00
This doesn't look good:

```
2017-10-23 12:11:09 ERROR parsing time "" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "2006"
```

**Comment by shlomi-noach** [comment] 2017-10-23 05:02
Can you verify replication works?

I personally haven't run `gh-ost` with MariaDB at all, but am under the impressions others have; the binlog parser _should_ work on `10.1`, I believe.

**Comment by NearTan** [comment] 2017-10-23 05:02
BTW: some `parsing time` errors in my output log, are they about socket issue?

**Comment by NearTan** [comment] 2017-10-23 05:06
@shlomi-noach I confirm that replication works well, should I upgrade to 10.1 or later

**Comment by shlomi-noach** [comment] 2017-10-23 06:03
@NearTan I believe you said you're on `10.1` which is why I mentioned `10.1` should work AFAIK

**Comment by NearTan** [comment] 2017-10-23 06:41
Sorry for my misunderstanding😄
So as I said, the replication works, but I found that `Seconds_Behind_Master` keeps increasing when hangs in `throttled` state, once I interrupt gh-ost, it increases to 0 soon.

**Comment by shlomi-noach** [comment] 2017-10-23 06:51
>  the replication works, but I found that Seconds_Behind_Master keeps increasing when hangs in throttled state, once I interrupt gh-ost, it increases to 0 soon.

That is exceedingly strange. So `gh-ost` is the very reason for the replica lagging, and if you Ctrl-C `gh-ost` everything's fine?
This sounds to me like a locking issue. I'm wondering whether you're using a thread pool?

**Comment by NearTan** [comment] 2017-10-23 07:14
> if you Ctrl-C gh-ost everything's fine?

everything is fine but output the same log as `Copy: 14000/784080`

> I'm wondering whether you're using a thread pool?

I am using cli to run, not thread pool code

**Comment by shlomi-noach** [comment] 2017-10-24 10:23
Interestingly, the `streamer:` output shows increasing positions in the binary logs.

Are you perhaps using multi source replication, or a flavor of replication that is different from "standard" oracle replication?

**Comment by NearTan** [comment] 2017-10-27 04:19
@shlomi-noach sorry for late reply.
I just use two containers to build that simple replication, I was use [bitnami/mariadb](https://github.com/bitnami/bitnami-docker-mariadb) image, but I recur this issue by [offical image](https://github.com/docker-library/mariadb).

Should I provide my create container commands?

**Comment by shlomi-noach** [comment] 2017-10-27 04:26
> Should I provide my create container commands?

Any data could be helpful

**Comment by NearTan** [comment] 2017-10-27 04:38
Add an entry to `/etc/hosts` for master container `127.0.0.1 master`

```
docker run -d --name mariadb-ost-rbr-m \
-e MARIADB_REPLICATION_MODE=master \
-e MARIADB_REPLICATION_USER=my_repl_user \
-e MARIADB_REPLICATION_PASSWORD=my_repl_password \
-e MARIADB_USER=my_user \
-e MARIADB_PASSWORD=my_password \
-e MARIADB_DATABASE=my_database \
-e ALLOW_EMPTY_PASSWORD=yes \
-e MARIADB_EXTRA_FLAGS='--port=33091 --binlog_format=ROW' \
-p 33091:33091 \
bitnami/mariadb:latest


docker run -d --name mariadb-ost-rbr-s --link mariadb-ost-rbr-m:master \
-e MARIADB_REPLICATION_MODE=slave \
-e MARIADB_REPLICATION_USER=my_repl_user \
-e MARIADB_REPLICATION_PASSWORD=my_repl_password \
-e MARIADB_MASTER_HOST=master \
-e MARIADB_MASTER_PORT_NUMBER=33091 \
-e ALLOW_EMPTY_PASSWORD=yes \
-e MARIADB_EXTRA_FLAGS='--port=33092 --binlog_format=ROW' \
-p 33092:33092 \
bitnami/mariadb:latest
```

**Comment by shlomi-noach** [comment] 2017-10-27 05:04
Thanks. That looks standard.

**Comment by everpcpc** [comment] 2018-01-10 04:53
Reproduced this issue.
I believe it's something with the heartbeat. Because when I set `heartbeat-interval-millis` to some value `>500ms`, everything goes well.

**Comment by everpcpc** [comment] 2018-01-10 09:35
Setting `this.db.SetMaxOpenConns(1)` in `InitDBConnections` seems to resolve this.
But still not sure why this happens yet.

**Comment by shlomi-noach** [comment] 2018-01-10 09:36
@everpcpc I still think your MySQL is configured to use a thread pool. Can you please double check?

**Comment by everpcpc** [comment] 2018-01-10 09:43
@shlomi-noach You mean the replication thread?

```
root@localhost [ttt] mysql> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: test00
                  Master_User: repl_user
                  Master_Port: 33091
                Connect_Retry: 10
              Master_Log_File: mysql-bin.000002
          Read_Master_Log_Pos: 175163327
               Relay_Log_File: mysql-relay-bin.000002
                Relay_Log_Pos: 1331425
        Relay_Master_Log_File: mysql-bin.000002
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 175163327
              Relay_Log_Space: 1331723
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 27399
               Master_SSL_Crl:
           Master_SSL_Crlpath:
                   Using_Gtid: Slave_Pos
                  Gtid_IO_Pos: 0-27399-49829
      Replicate_Do_Domain_Ids:
  Replicate_Ignore_Domain_Ids:
                Parallel_Mode: none
1 row in set (0.00 sec)
```
And during the migration:
```
root@localhost [ttt] mysql> show processlist;
+-----+-------------+-------------------+--------------------+-------------+------+-----------------------------------------------------------------------+------------------+----------+
| Id  | User        | Host              | db                 | Command     | Time | State                                                                 | Info             | Progress |
+-----+-------------+-------------------+--------------------+-------------+------+-----------------------------------------------------------------------+------------------+----------+
| 280 | root        | 172.17.42.1:41742 | ttt                | Query       |    0 | init                                                                  | show processlist |    0.000 |
| 486 | root        | 172.17.42.1:15658 | ttt                | Sleep       |    0 |                                                                       | NULL             |    0.000 |
| 487 | root        | 172.17.42.1:15686 | information_schema | Sleep       |   18 |                                                                       | NULL             |    0.000 |
| 488 | system user |                   | NULL               | Connect     |   21 | Waiting for master to send event                                      | NULL             |    0.000 |
| 489 | system user |                   | NULL               | Connect     |    0 | Unlocking tables                                                      | NULL             |    0.000 |
| 490 | root        | 172.17.42.1:19234 | NULL               | Binlog Dump |   21 | Master has sent all binlog to slave; waiting for binlog to be updated | NULL             |    0.000 |
+-----+-------------+-------------------+--------------------+-------------+------+-----------------------------------------------------------------------+------------------+----------+
```

**Comment by shlomi-noach** [comment] 2018-01-10 09:51
No, I mean the internal thread pool MySQL config. It's `thread_handling=pool-of-threads` on Oracle MySQL. Or `show global variables like '%thread%'` or `show global status like '%thread%'`

**Comment by shlomi-noach** [comment] 2018-01-10 09:53
You're using MariaDB, that's https://mariadb.com/kb/en/library/thread-pool-in-mariadb/

**Comment by shlomi-noach** [comment] 2018-01-10 10:24
OK, so no thread pooling.

**Comment by zmoazeni** [comment] 2018-01-10 14:55
What is the global `max_connections` variable set to? If it's <=25, gh-ost could be consuming all available connections to MySQL early.

**Comment by everpcpc** [comment] 2018-01-11 03:01
@zmoazeni `max_connections` on both slave and master was default set to 151.

**Comment by everpcpc** [comment] 2018-01-12 08:07
Hi @shlomi-noach @zmoazeni ,
I've tested with this script:
```
package main

import (
	"database/sql"
	_ "github.com/go-sql-driver/mysql"
	"log"
	"time"
)

func update(server, id, hint string, tick int) {
	db, _ := sql.Open("mysql", server)
	db.SetMaxOpenConns(1)

	t := time.Now().UnixNano()
	_, err := db.Exec(`insert into xxx (id, hint, value) values (?, ?, ?)`, id, hint, t)
	if err != nil {
		log.Println(hint, err)
	}

	count := 1
	last := t
	ticker := time.Tick(time.Duration(tick) * time.Millisecond)
	for range ticker {
		t = time.Now().UnixNano()
		_, err = db.Exec(`update xxx set value=? where id=?`, t, id)
		if err != nil {
			log.Println(hint, err)
		}
		count++
		if count%10 == 0 {
			avg := float64(count) / float64(t-last) * 10e8
			log.Printf("%s: %.2f /s\n", hint, avg)
			last = t
			count = 0
		}
	}
}

func main() {
	server := "root:@tcp(localhost:33081)/ttt?interpolateParams=true&autocommit=1&charset=utf8mb4,utf8,latin1"

	db, _ := sql.Open("mysql", server)
	db.SetMaxOpenConns(1)
	if _, err := db.Exec(`DROP TABLE IF EXISTS xxx`); err != nil {
		panic(err)
	}
	if _, err := db.Exec(`
	CREATE TABLE xxx (
		id int(10) NOT NULL AUTO_INCREMENT,
		hint varchar(64) CHARACTER SET ascii NOT NULL,
		value varchar(4096) CHARACTER SET ascii NOT NULL,
		PRIMARY KEY (id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8
	`); err != nil {
		panic(err)
	}
	db.Close()

	// go update(server, "4", "t4")
	// go update(server, "3", "t3")
	// go update(server, "2", "t2")
	update(server, "1", "t1", 100)
}
```
And it turns out to be a performance issue.
When updating with 2 goroutines at 100ms, the lag on slave keeps increasing.

But if only 1 connection is used, then performance is limited, so gh-ost keeps going.

Therefore, maybe it's better to limit the connection to only 1 in case the heartbeat it self causing the lag on slave? Or the heartbeat rate could be set slower?

**Comment by everpcpc** [comment] 2018-02-05 08:31
The performance issue seems to be caused by the default `sync_binlog=1` and `innodb_flush_log_at_trx_commit=1`.
With this two options set, a row can only be updated around 10 times per second on my mariadb instance.
And with`innodb_flush_log_at_trx_commit=2`, the update rate can reaches around 25/s.
So setting this on slave, then `gh-ost` runs smoothly without throttling.

**Comment by shlomi-noach** [comment] 2018-02-06 06:44
> With this two options set, a row can only be updated around 10 times per second on my mariadb instance.

That's unreasonably low. Is your machine otherwise heavily loaded?

**Comment by everpcpc** [comment] 2018-02-06 09:46
It seems a problem with disk I/O  performance.
The test server is a xen virtual machine with some other vms on the host. So, not sure.
I tried another free physical machine and it's about 39 /s.
My macbook with ssd reaches around 180 /s.
😆

**Comment by shlomi-noach** [comment] 2018-09-17 06:12
closing this as this seems to be solved

**Closed by shlomi-noach** 2018-09-17 06:12 UTC
