### ISSUE TITLE
Error with renamed column 

### ISSUE THREAD

**Issue by ggunson** [github/gh-ost#178] opened 2016-08-19 21:54 UTC
Running a migration that changed the name of a column, as well as added an index on the (newly named) column, it eventually died with this message:

```
2016-08-19 14:37:46 ERROR shared columns is not a subset of table columns in BuildDMLUpdateQuery
2016-08-19 14:37:46 FATAL shared columns is not a subset of table columns in BuildDMLUpdateQuery
```

This was after a 40 minute long `select count(*)`, which looks like it could be hitting a bug with MySQL 5.7 (https://bugs.mysql.com/bug.php?id=80580), so I'm guessing it got past the initial schema checks.

Command was:

```
gh-ost-wrapper-script -c mysql1 -t tablename -d 'CHANGE old_column new_column int(11) DEFAULT NULL,ADD INDEX index_1 (new_column),ADD INDEX index_2 (column_whocares, column_fine),DROP INDEX shitty_index' -x -- --approve-renamed-columns 
```

cc @github/database-infrastructure this is blocking a migration

**Comment by shlomi-noach** [comment] 2016-08-22 05:53
I am able to reproduce this. This error happens for any `rename` and `update`.

**Comment by shlomi-noach** [comment] 2016-08-22 05:55
> This was after a 40 minute long select count(*), which looks like it could be hitting a bug with MySQL 5.7 (https://bugs.mysql.com/bug.php?id=80580), so I'm guessing it got past the initial schema checks.

The bug happens while handling an `UPDATE` event in the binary log. This is the reason why `gh-ost` only crashed 40 minutes into the execution: everything was sound and fine in terms of schema change, and `count(*)` took a long time; the problem only manifested while applying changes read from the binary log.

**Comment by shlomi-noach** [comment] 2016-08-22 05:57
Fix is under way.

**Comment by shlomi-noach** [comment] 2016-08-22 10:09
Fix sent to testing

**Comment by shlomi-noach** [comment] 2016-08-22 13:53
`UPDATE` is fixed. Still have `INSERT` issue.

**Comment by shlomi-noach** [comment] 2016-08-22 14:08
Sent to testing

**Comment by shlomi-noach** [comment] 2016-08-23 06:00
Testing passes. `INSERT` fix merged. Will soon release.

**Comment by shlomi-noach** [comment] 2016-08-24 07:32
`1.0.13` fixes this

**Closed by shlomi-noach** 2016-08-24 07:32 UTC
Labels: bug
