### ISSUE TITLE
StreamEvents encountered unexpected error: data len 1259 < expected 14985

### ISSUE THREAD

**Issue by mardachevdv** [github/gh-ost#509] opened 2017-10-25 20:36 UTC
Hi, 

when I try to alter table I always have the same error 

```
Copy: 85118000/117939928 72.2%; Applied: 60049; Backlog: 0/1000; Time: 5h1m20s(total), 5h1m20s(copy); streamer: dbcn02-bin.000013:339139251; State: migrating; ETA: 1h56m11s
Copy: 85138000/117939928 72.2%; Applied: 60049; Backlog: 0/1000; Time: 5h1m25s(total), 5h1m25s(copy); streamer: dbcn02-bin.000013:469610748; State: migrating; ETA: 1h56m7s
Copy: 85156000/117939928 72.2%; Applied: 60049; Backlog: 0/1000; Time: 5h1m30s(total), 5h1m30s(copy); streamer: dbcn02-bin.000013:601846216; State: migrating; ETA: 1h56m4s
2017/10/25 12:10:19 binlogstreamer.go:47: [error] close sync with err: data len 1259 < expected 14985
2017-10-25 12:10:19 INFO StreamEvents encountered unexpected error: data len 1259 < expected 14985
Copy: 85176000/117939928 72.2%; Applied: 60049; Backlog: 0/1000; Time: 5h1m35s(total), 5h1m35s(copy); streamer: dbcn02-bin.000013:635376151; State: migrating; ETA: 1h56m0s
2017-10-25 12:10:24 FATAL 61 successive failures in streamer reconnect at coordinates dbcn02-bin.000013:4
```

gh-ost --version
1.0.42

mysql
5.7.18-15-57-log | Percona XtraDB Cluster (GPL), Release rel15, Revision 7693d6e, WSREP version 29.20, wsrep_29.20

my command was
> /opt/gh-ost/gh-ost --allow-on-master --allow-master-master --switch-to-rbr --timestamp-old-table --verbose --max-load=Threads_running=25 --critical-load=Threads_running=1000 --chunk-size=2000 --max-lag-millis=1500 --default-retries=60 --conf=/path/to/my.cnf --critical-load-interval-millis=2500 --discard-foreign-keys --cut-over=two-step --panic-flag-file=/tmp/ghost.panic.flag --postpone-cut-over-flag-file=/tmp/ghost.postpone.flag --host="master" --port=3306 --assume-master-host="master" --database="db" --table="table" --alter="engine=innodb" --execute

table I want to alter
```
CREATE TABLE `user_chat_messages` (
  `userChatMessageId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `chatMessageId` bigint(20) unsigned DEFAULT NULL,
  `userId` bigint(20) unsigned DEFAULT NULL,
  `isRead` tinyint(4) DEFAULT NULL,
  `isDeleted` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`userChatMessageId`),
  KEY `chatMessageId` (`chatMessageId`),
  KEY `userId` (`userId`),
  KEY `isRead` (`isRead`),
  KEY `isDeleted` (`isDeleted`),
  CONSTRAINT `user_chat_messages_ibfk_1` FOREIGN KEY (`chatMessageId`) REFERENCES `chat_messages` (`chatMessageId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_chat_messages_ibfk_3` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=456428768 DEFAULT CHARSET=utf8
```

Thanks for any help on this

**Comment by shlomi-noach** [comment] 2017-10-26 13:21
I'm baffled at this time and it seems like a problem with the `go-mysql` library.

**Comment by shlomi-noach** [comment] 2017-10-26 13:23
Since you're using `XtraDB cluster`, you might be interested in https://github.com/github/gh-ost/issues/224

I don't know that `gh-ost` would run well on Galera/XtraDB Cluster ; though I also don't think the problem in this Issue is related to Galera.

**Comment by mardachevdv** [comment] 2017-10-26 14:32
more information with enabled debug  
> 2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992892794
2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992900983
2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992909172
2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992917361
2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992925550
2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992933739
2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992941928
2017/10/26 09:26:49 binlogstreamer.go:47: [error] close sync with err: data len 980 < expected 13063
2017-10-26 09:26:49 DEBUG Skipping handled query at dbcn02-bin.000023:992950117
2017-10-26 09:26:49 INFO StreamEvents encountered unexpected error: data len 980 < expected 13063
Copy: 112770000/118140844 95.5%; Applied: 41328; Backlog: 0/1000; Time: 4h22m55s(total), 4h22m55s(copy); streamer: dbcn02-bin.000023:992950117; State: migrating; ETA: 12m31s
2017-10-26 09:26:50 DEBUG Issued INSERT on range: [374325795]..[374350795]; iteration: 22554; chunk-size: 5000
2017-10-26 09:26:50 DEBUG Issued INSERT on range: [374350795]..[374375795]; iteration: 22555; chunk-size: 5000
2017-10-26 09:26:51 DEBUG Issued INSERT on range: [374375795]..[374400795]; iteration: 22556; chunk-size: 5000
2017-10-26 09:26:51 DEBUG Issued INSERT on range: [374400795]..[374425795]; iteration: 22557; chunk-size: 5000


and we have error im mysql error log
> 2017-10-26T14:23:04.199614Z 8190528 [Note] While initializing dump thread for slave with server_id <99999>, found a zombie dump thread with the same server_id. Master is killing the zombie dump thread(8188642).
2017-10-26T14:23:04.199708Z 8190528 [Note] Start binlog_dump to master_thread_id(8190528) slave_server(99999), pos(dbcn02-bin.000023, 4)

**Comment by shlomi-noach** [comment] 2017-10-26 16:01
For sake of experiment, can you please try with `-replica-server-id=12345` and confirm that's what MySQL kills?

**Comment by mardachevdv** [comment] 2017-10-26 16:42
ok, I will try tomorrow
thanks for help

**Comment by mardachevdv** [comment] 2017-10-27 07:13
with --replica-server-id=12345 

> 2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832709710
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832717899
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832726088
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832734277
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832742466
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832750655
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832758844
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832763415
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832763716
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832764020
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832764353
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832764743
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832765164
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832765465
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832765769
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832766078
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832766379
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832766683
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832766992
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832767413
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832768008
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832768633
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832769054
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832769765
2017/10/27 01:54:36 binlogstreamer.go:47: [error] close sync with err: data len 976 < expected 13959
2017-10-27 01:54:36 DEBUG Skipping handled query at dbcn02-bin.000030:832770102
2017-10-27 01:54:36 DEBUG Issued INSERT on range: [163417017]..[163432017]; iteration: 12385; chunk-size: 5000
2017-10-27 01:54:36 INFO StreamEvents encountered unexpected error: data len 976 < expected 13959
2017-10-27 01:54:37 DEBUG Issued INSERT on range: [163432017]..[163447017]; iteration: 12386; chunk-size: 5000
2017-10-27 01:54:37 DEBUG Issued INSERT on range: [163447017]..[163462017]; iteration: 12387; chunk-size: 5000


mysql error log
> 2017-10-27T06:50:58.132277Z 10826330 [Note] While initializing dump thread for slave with server_id <12345>, found a zombie dump thread with the same server_id. Master is killing the zombie dump thread(10597592).
2017-10-27T06:50:58.132378Z 10826330 [Note] Start binlog_dump to master_thread_id(10826330) slave_server(12345), pos(dbcn02-bin.000030, 4)
2017-10-27T06:51:34.385672Z 10827221 [Note] While initializing dump thread for slave with server_id <12345>, found a zombie dump thread with the same server_id. Master is killing the zombie dump thread(10826330).
2017-10-27T06:51:34.385806Z 10827221 [Note] Start binlog_dump to master_thread_id(10827221) slave_server(12345), pos(dbcn02-bin.000030, 4)
2017-10-27T06:51:34.390679Z 10826330 [Note] Aborted connection 10826330 to db: 'unconnected' user: 'root' host: '10.31.1.202' (A slave with the same server_uuid/server_id as this slave has co)
2017-10-27T06:52:11.497771Z 10828285 [Note] While initializing dump thread for slave with server_id <12345>, found a zombie dump thread with the same server_id. Master is killing the zombie dump thread(10827221).
2017-10-27T06:52:11.497860Z 10828285 [Note] Start binlog_dump to master_thread_id(10828285) slave_server(12345), pos(dbcn02-bin.000030, 4)
2017-10-27T06:52:11.501072Z 10827221 [Note] Aborted connection 10827221 to db: 'unconnected' user: 'root' host: '10.31.1.202' (A slave with the same server_uuid/server_id as this slave has co)
2017-10-27T06:52:48.606309Z 10829231 [Note] While initializing dump thread for slave with server_id <12345>, found a zombie dump thread with the same server_id. Master is killing the zombie dump thread(10828285).
2017-10-27T06:52:48.606434Z 10829231 [Note] Start binlog_dump to master_thread_id(10829231) slave_server(12345), pos(dbcn02-bin.000030, 4)
2017-10-27T06:52:48.617553Z 10828285 [Note] Aborted connection 10828285 to db: 'unconnected' user: 'root' host: '10.31.1.202' (A slave with the same server_uuid/server_id as this slave has co)
2017-10-27T06:53:24.781819Z 10830223 [Note] While initializing dump thread for slave with server_id <12345>, found a zombie dump thread with the same server_id. Master is killing the zombie dump thread(10829231).
2017-10-27T06:53:24.781918Z 10830223 [Note] Start binlog_dump to master_thread_id(10830223) slave_server(12345), pos(dbcn02-bin.000030, 4)
2017-10-27T06:53:24.787398Z 10829231 [Note] Aborted connection 10829231 to db: 'unconnected' user: 'root' host: '10.31.1.202' (A slave with the same server_uuid/server_id as this slave has co)
2017-10-27T06:54:02.025814Z 10831258 [Note] While initializing dump thread for slave with server_id <12345>, found a zombie dump thread with the same server_id. Master is killing the zombie dump thread(10830223).
2017-10-27T06:54:02.026025Z 10831258 [Note] Start binlog_dump to master_thread_id(10831258) slave_server(12345), pos(dbcn02-bin.000030, 4)
2017-10-27T06:54:02.033122Z 10830223 [Note] Aborted connection 10830223 to db: 'unconnected' user: 'root' host: '10.31.1.202' (A slave with the same server_uuid/server_id as this slave has co)
2017-10-27T06:54:37.658803Z 10832285 [Note] Aborted connection 10832285 to db: ‘db_3’ user: 'root' host: '10.31.1.202' (Got an error reading communication packets)
2017-10-27T06:54:37.658794Z 10597590 [Note] Aborted connection 10597590 to db: 'information_schema' user: 'root' host: '10.31.1.202' (Got an error reading communication packets)
2017-10-27T06:54:37.658794Z 10597594 [Note] Aborted connection 10597594 to db: 'db_3' user: 'root' host: '10.31.1.202' (Got an error reading communication packets)
2017-10-27T06:54:37.658830Z 10832231 [Note] Aborted connection 10832231 to db: 'db_3' user: 'root' host: '10.31.1.202' (Got an error reading communication packets)
2017-10-27T06:54:37.659034Z 10831258 [Note] Aborted connection 10831258 to db: 'unconnected' user: 'root' host: '10.31.1.202' (Failed on my_net_write())

**Comment by mardachevdv** [comment] 2017-10-30 15:19
looks like something wrong with default --dml-batch-size=10
everything is ok with --dml-batch-size=1

**Comment by shlomi-noach** [comment] 2017-10-30 18:41
That's an unexpected observation. Thank you for investigating this! I don't have an immediate enlightenment given this observation 😮

**Comment by shlomi-noach** [comment] 2017-11-20 06:24
A hunch: what is your `select @@global.max_allowed_packet`?

**Comment by mardachevdv** [comment] 2017-11-20 06:55
1073741824

**Comment by boomballa** [comment] 2022-12-22 03:27
@shlomi-noach  Hello, is this problem accurately located? I'm also running into this kind of problem right now.
Although it can be solved by using the latest version, I am still curious as to what is causing it.
The problem is that not all tables will have this kind of problem, most of them are normal, only a few tables will have this problem stably, so I would like to consult you again.

**Comment by timvaillancourt** [comment] 2022-12-23 20:07
@mardachevdv / @boomballa could you please retry on [the latest stable version of `gh-ost`](https://github.com/github/gh-ost/releases/tag/v1.1.5)? This version uses a newer version of the `go-mysql` library

I will close this issue for now as we don't see this on recent versions, but please open a new issue if you do see this on 1.1.5+ 🙇

**Closed by timvaillancourt** 2022-12-23 20:07 UTC

**Comment by boomballa** [comment] 2022-12-26 08:37
@timvaillancourt  Thank you very much for your reply. I have verified that this problem does not occur in version 1.0.45. I saw that it was written in the changelog of version 1.0.45: Fix to long JSON values.
I also verified that my data does exist in the json field, and when the length is greater than 300, this problem will always occur.
I tried to check go-mysql, and found that the problem appeared on json_binary.go. From the perspective of learning, I was just curious why it appeared before, but it did not appear again after the subsequent version was fixed. What is the trigger logic of this bug?

**Comment by timvaillancourt** [comment] 2022-12-27 18:44
> I was just curious why it appeared before, but it did not appear again after the subsequent version was fixed. What is the trigger logic of this bug?

@boomballa thanks for the feedback

Unfortunately I don't know how this bug was fixed in `go-mysql`, I just know `gh-ost` users don't see this on recent versions that use a more-recent version of `go-mysql`

**Comment by boomballa** [comment] 2022-12-29 07:22
@timvaillancourt  Ok, thank you for your reply. Specifically, I will check the relevant repair and iteration records of go-mysql.
Thank you very much.

**Comment by boomballa** [comment] 2022-12-29 07:24
> > I was just curious why it appeared before, but it did not appear again after the subsequent version was fixed. What is the trigger logic of this bug?
> 
> @boomballa thanks for the feedback
> 
> Unfortunately I don't know how this bug was fixed in `go-mysql`, I just know `gh-ost` users don't see this on recent versions that use a more-recent version of `go-mysql`

@timvaillancourt Ok, thank you for your reply. Specifically, I will check the relevant repair and iteration records of go-mysql.
Thank you very much.
