### ISSUE TITLE
binlogstreamer.go "close sync with err" on Tungsten cluster

### ISSUE THREAD

**Issue by johnz1** [github/gh-ost#383] opened 2017-03-15 20:20 UTC
gh-ost 1.0.35
MySQL 5.6.23
Tungsten 4.0.7

Hello

I'm running gh-ost against the master of a Tungsten 4.0.7 cluster.  I'm trying to drop a column, but it's giving the following error for binlogstreamer:

`binlogstreamer.go:47: [error] close sync with err: sync is been closing...`

Here's the full output:

```
2017-03-15 16:11:20 INFO starting gh-ost 1.0.35
2017-03-15 16:11:20 INFO Migrating `db`.`tbl`
2017-03-15 16:11:20 INFO connection validated on testhost:13306
2017-03-15 16:11:20 INFO User has ALL privileges
2017-03-15 16:11:20 INFO binary logs validated on testhost:13306
2017-03-15 16:11:20 INFO Restarting replication on testhost:13306 to make sure binlog settings apply to replication thread
2017-03-15 16:11:20 INFO Inspector initiated on testhost:13306, version 5.6.23-enterprise-commercial-advanced-log
2017-03-15 16:11:20 INFO Table found. Engine=InnoDB
2017-03-15 16:11:20 INFO Estimated number of rows via EXPLAIN: 10
2017-03-15 16:11:20 INFO Master forced to be testhost:13306
2017-03-15 16:11:20 WARNING log_slave_updates not found on testhost:13306, but --tungsten provided, so I'm proceeding
2017-03-15 16:11:20 INFO connection validated on testhost:13306
2017/03/15 16:11:20 binlogsyncer.go:75: [info] create BinlogSyncer with config &{99999 mysql testhost 13306 mwadmin passwd  false false <nil>}
2017-03-15 16:11:20 INFO Connecting binlog streamer at mysql-bin.000044:13138
2017/03/15 16:11:20 binlogsyncer.go:241: [info] begin to sync binlog from position (mysql-bin.000044, 13138)
2017/03/15 16:11:20 binlogsyncer.go:134: [info] register slave for master server testhost:13306
2017/03/15 16:11:20 binlogsyncer.go:568: [info] rotate to (mysql-bin.000044, 13138)
2017-03-15 16:11:20 INFO rotate to next log name: mysql-bin.000044
2017-03-15 16:11:20 INFO connection validated on testhost:13306
2017-03-15 16:11:20 INFO connection validated on testhost:13306
2017-03-15 16:11:20 INFO will use time_zone='SYSTEM' on applier
2017-03-15 16:11:20 INFO Examining table structure on applier
2017-03-15 16:11:20 INFO Applier initiated on testhost:13306, version 5.6.23-enterprise-commercial-advanced-log
2017-03-15 16:11:20 INFO Droppping table `db`.`_tbl_gho`
2017-03-15 16:11:20 INFO Table dropped
2017-03-15 16:11:20 INFO Droppping table `db`.`_tbl_del`
2017-03-15 16:11:20 INFO Table dropped
2017-03-15 16:11:20 INFO Droppping table `db`.`_tbl_ghc`
2017-03-15 16:11:20 INFO Table dropped
2017-03-15 16:11:20 INFO Creating changelog table `db`.`_tbl_ghc`
2017-03-15 16:11:20 INFO Changelog table created
2017-03-15 16:11:20 INFO Creating ghost table `db`.`_tbl_gho`
2017-03-15 16:11:20 INFO Ghost table created
2017-03-15 16:11:20 INFO Altering ghost table `db`.`_tbl_gho`
2017-03-15 16:11:20 INFO Ghost table altered
2017-03-15 16:11:20 INFO Intercepted changelog state GhostTableMigrated
2017-03-15 16:11:20 INFO Waiting for ghost table to be migrated. Current lag is 0s
2017-03-15 16:11:20 INFO Handled changelog state GhostTableMigrated
2017-03-15 16:11:20 INFO Chosen shared unique key is PRIMARY
2017-03-15 16:11:20 INFO Shared columns are id,username,firstname,date
2017-03-15 16:11:20 INFO Listening on unix socket file: /tmp/gh-ost.db.tbl.sock
2017-03-15 16:11:20 INFO Migration min values: [1]
2017-03-15 16:11:20 INFO Migration max values: [10]
2017-03-15 16:11:20 INFO Waiting for first throttle metrics to be collected
2017-03-15 16:11:20 INFO First throttle metrics collected
# Migrating `db`.`tbl`; Ghost table is `db`.`_tbl_gho`
# Migrating testhost:13306; inspecting testhost:13306; executing on mysqlmon-00-ah
# Migration started at Wed Mar 15 16:11:20 -0400 2017
2017-03-15 16:11:20 INFO Row copy complete
# Migrating `db`.`tbl`; Ghost table is `db`.`_tbl_gho`
# chunk-size: 1000; max-lag-millis: 180000ms; max-load: Threads_running=25; critical-load: Threads_running=1000; nice-ratio: 0.000000
# Migrating testhost:13306; inspecting testhost:13306; executing on mysqlmon-00-ah
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# Migration started at Wed Mar 15 16:11:20 -0400 2017
# chunk-size: 1000; max-lag-millis: 180000ms; max-load: Threads_running=25; critical-load: Threads_running=1000; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# postpone-cut-over-flag-file: /tmp/ghost.postpone.flag
# panic-flag-file: /tmp/ghost.panic.flag
# postpone-cut-over-flag-file: /tmp/ghost.postpone.flag
# Serving on unix socket: /tmp/gh-ost.db.tbl.sock
# panic-flag-file: /tmp/ghost.panic.flag
# Serving on unix socket: /tmp/gh-ost.db.tbl.sock
Copy: 0/0 100.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: mysql-bin.000044:14927; State: migrating; ETA: due
2017-03-15 16:11:20 INFO New table structure follows
CREATE TABLE `_tbl_gho` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(16) NOT NULL,
  `firstname` varchar(50) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
2017/03/15 16:11:20 binlogsyncer.go:102: [info] syncer is closing...
2017/03/15 16:11:20 binlogstreamer.go:47: [error] close sync with err: sync is been closing...
2017/03/15 16:11:20 binlogsyncer.go:117: [info] syncer is closed
2017-03-15 16:11:20 INFO Closed streamer connection. err=<nil>
2017-03-15 16:11:20 INFO Droppping table `db`.`_tbl_ghc`
Copy: 0/10 0.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: mysql-bin.000044:14927; State: migrating; ETA: N/A
2017-03-15 16:11:20 INFO Table dropped
2017-03-15 16:11:20 INFO Droppping table `db`.`_tbl_gho`
2017-03-15 16:11:20 INFO Table dropped
2017-03-15 16:11:20 INFO Done migrating `db`.`tbl`
2017-03-15 16:11:20 INFO Removing socket file: /tmp/gh-ost.db.tbl.sock
# Done
```

I'm not sure where to go from here.  Is there any way to get more info on the error that binlogstreamer is encountering?

Thank you

**Comment by shlomi-noach** [comment] 2017-03-15 20:34
This is an error in the `go-mysql` underlying library. Please run again with `--debug` and paste output, perhaps we can get more insight.

**Comment by johnz1** [comment] 2017-03-15 20:44
Yes, here it is:

```
2017-03-15 16:37:49 INFO starting gh-ost 1.0.35
2017-03-15 16:37:49 INFO Migrating `db`.`tbl`
2017-03-15 16:37:49 INFO connection validated on testhost:13306
2017-03-15 16:37:49 INFO User has ALL privileges
2017-03-15 16:37:49 INFO binary logs validated on testhost:13306
2017-03-15 16:37:49 INFO Restarting replication on testhost:13306 to make sure binlog settings apply to replication thread
2017-03-15 16:37:49 INFO Inspector initiated on testhost:13306, version 5.6.23-enterprise-commercial-advanced-log
2017-03-15 16:37:49 INFO Table found. Engine=InnoDB
2017-03-15 16:37:49 DEBUG Estimated number of rows via STATUS: 10
2017-03-15 16:37:49 DEBUG Validated no foreign keys exist on table
2017-03-15 16:37:49 DEBUG Validated no triggers exist on table
2017-03-15 16:37:49 INFO Estimated number of rows via EXPLAIN: 10
2017-03-15 16:37:49 DEBUG Potential unique keys in tbl: [PRIMARY (auto_increment): [id]; has nullable: false]
2017-03-15 16:37:49 INFO Master forced to be testhost:13306
2017-03-15 16:37:49 WARNING log_slave_updates not found on testhost:13306, but --tungsten provided, so I'm proceeding
2017-03-15 16:37:49 INFO connection validated on testhost:13306
2017-03-15 16:37:49 DEBUG Streamer binlog coordinates: mysql-bin.000044:16117
2017/03/15 16:37:49 binlogsyncer.go:75: [info] create BinlogSyncer with config &{99999 mysql testhost 13306 mwadmin passwd  false false <nil>}
2017-03-15 16:37:49 INFO Connecting binlog streamer at mysql-bin.000044:16117
2017/03/15 16:37:49 binlogsyncer.go:241: [info] begin to sync binlog from position (mysql-bin.000044, 16117)
2017/03/15 16:37:49 binlogsyncer.go:134: [info] register slave for master server testhost:13306
2017-03-15 16:37:49 DEBUG Beginning streaming
2017/03/15 16:37:49 binlogsyncer.go:568: [info] rotate to (mysql-bin.000044, 16117)
2017-03-15 16:37:49 INFO rotate to next log name: mysql-bin.000044
2017-03-15 16:37:49 INFO connection validated on testhost:13306
2017-03-15 16:37:49 INFO connection validated on testhost:13306
2017-03-15 16:37:49 INFO will use time_zone='SYSTEM' on applier
2017-03-15 16:37:49 INFO Examining table structure on applier
2017-03-15 16:37:49 INFO Applier initiated on testhost:13306, version 5.6.23-enterprise-commercial-advanced-log
2017-03-15 16:37:49 INFO Droppping table `db`.`_tbl_gho`
2017-03-15 16:37:49 INFO Table dropped
2017-03-15 16:37:49 INFO Droppping table `db`.`_tbl_del`
2017-03-15 16:37:49 INFO Table dropped
2017-03-15 16:37:49 INFO Droppping table `db`.`_tbl_ghc`
2017-03-15 16:37:49 INFO Table dropped
2017-03-15 16:37:49 INFO Creating changelog table `db`.`_tbl_ghc`
2017-03-15 16:37:49 INFO Changelog table created
2017-03-15 16:37:49 INFO Creating ghost table `db`.`_tbl_gho`
2017-03-15 16:37:49 INFO Ghost table created
2017-03-15 16:37:49 INFO Altering ghost table `db`.`_tbl_gho`
2017-03-15 16:37:49 DEBUG ALTER statement: alter /* gh-ost */ table `db`.`_tbl_gho` DROP COLUMN lastname
2017-03-15 16:37:49 INFO Ghost table altered
2017-03-15 16:37:49 INFO Intercepted changelog state GhostTableMigrated
2017-03-15 16:37:49 INFO Waiting for ghost table to be migrated. Current lag is 0s
2017-03-15 16:37:49 DEBUG ghost table migrated
2017-03-15 16:37:49 INFO Handled changelog state GhostTableMigrated
2017-03-15 16:37:49 DEBUG Potential unique keys in _tbl_gho: [PRIMARY (auto_increment): [id]; has nullable: false]
2017-03-15 16:37:49 INFO Chosen shared unique key is PRIMARY
2017-03-15 16:37:49 INFO Shared columns are id,username,firstname,date
2017-03-15 16:37:49 INFO Listening on unix socket file: /tmp/gh-ost.db.tbl.sock
2017-03-15 16:37:49 DEBUG Reading migration range according to key: PRIMARY
2017-03-15 16:37:49 INFO Migration min values: [1]
2017-03-15 16:37:49 DEBUG Reading migration range according to key: PRIMARY
2017-03-15 16:37:49 INFO Migration max values: [10]
2017-03-15 16:37:49 INFO Waiting for first throttle metrics to be collected
2017-03-15 16:37:49 INFO First throttle metrics collected
2017-03-15 16:37:49 DEBUG Operating until row copy is complete
2017-03-15 16:37:49 DEBUG Noop operation; not really executing write funcs
# Migrating `db`.`tbl`; Ghost table is `db`.`_tbl_gho`
# Migrating testhost:13306; inspecting testhost:13306; executing on mysqlmon-00-ah
# Migration started at Wed Mar 15 16:37:49 -0400 2017
2017-03-15 16:37:49 DEBUG Noop operation; not really copying data
# chunk-size: 1000; max-lag-millis: 180000ms; max-load: Threads_running=25; critical-load: Threads_running=1000; nice-ratio: 0.000000
2017-03-15 16:37:49 INFO Row copy complete
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# Migrating `db`.`tbl`; Ghost table is `db`.`_tbl_gho`
# postpone-cut-over-flag-file: /tmp/ghost.postpone.flag
# panic-flag-file: /tmp/ghost.panic.flag
# Serving on unix socket: /tmp/gh-ost.db.tbl.sock
# Migrating testhost:13306; inspecting testhost:13306; executing on mysqlmon-00-ah
# Migration started at Wed Mar 15 16:37:49 -0400 2017
# chunk-size: 1000; max-lag-millis: 180000ms; max-load: Threads_running=25; critical-load: Threads_running=1000; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# postpone-cut-over-flag-file: /tmp/ghost.postpone.flag
# panic-flag-file: /tmp/ghost.panic.flag
# Serving on unix socket: /tmp/gh-ost.db.tbl.sock
Copy: 0/10 0.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: mysql-bin.000044:17906; State: migrating; ETA: N/A
Copy: 0/0 100.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: mysql-bin.000044:17906; State: migrating; ETA: due
2017-03-15 16:37:49 DEBUG Noop operation; not really swapping tables
2017-03-15 16:37:49 DEBUG done streaming events
2017-03-15 16:37:49 INFO New table structure follows
CREATE TABLE `_tbl_gho` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(16) NOT NULL,
  `firstname` varchar(50) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
2017/03/15 16:37:49 binlogsyncer.go:102: [info] syncer is closing...
2017/03/15 16:37:49 binlogstreamer.go:47: [error] close sync with err: sync is been closing...
2017/03/15 16:37:49 binlogsyncer.go:117: [info] syncer is closed
2017-03-15 16:37:49 INFO Closed streamer connection. err=<nil>
2017-03-15 16:37:49 INFO Droppping table `db`.`_tbl_ghc`
2017-03-15 16:37:49 INFO Table dropped
2017-03-15 16:37:49 INFO Droppping table `db`.`_tbl_gho`
2017-03-15 16:37:49 INFO Table dropped
2017-03-15 16:37:49 INFO Done migrating `db`.`tbl`
2017-03-15 16:37:49 INFO Removing socket file: /tmp/gh-ost.db.tbl.sock
# Done
```

**Comment by siddontang** [comment] 2017-03-16 01:25
> syncer is closing...

It means that gh-ost closes the replication explicitly outside.

**Comment by shlomi-noach** [comment] 2017-03-16 04:28
> It means that gh-ost closes the replication explicitly outside.

That makes sense, though I need to see if this reproduces on my side.

@johnz1 these errors, while bothersome, do not reflect a problem in your migration. I'll look into making them go away, and it seems like I try to close a connection that has already been closed.

This error reflects the "streamer" connection, which is what listens to binary log events. However you will note it happens after migration has cut-over (or, since you _noop_ped, after what would be the cut-over), and at that time the streamer is not used anymore.

**Comment by johnz1** [comment] 2017-03-16 17:12
Hmm I dont understand why it's using "noop".  I ran with '-execute'

```
./gh-ost \
--max-load=Threads_running=25 \
--critical-load=Threads_running=1000 \
--chunk-size=1000 \
--max-lag-millis=180000 \
--user="username" \
--password="password" \
--host=testhost \
--port=13306 \
--allow-on-master \
--database="db" \
--table="tbl" \
--verbose \
--alter="DROP COLUMN lastname" \
--switch-to-rbr \
--cut-over=default \
--default-retries=120 \
--panic-flag-file=/tmp/ghost.panic.flag \
--postpone-cut-over-flag-file=/tmp/ghost.postpone.flag \
--assume-master-host=testhost:13306 \
--initially-drop-ghost-table \
--initially-drop-old-table \
--tungsten \
--debug \
–execute
```

**Comment by shlomi-noach** [comment] 2017-03-16 17:38
@johnz1 the "dash" preceeding `execute` in your pasted command is not a real dash. Compare `-` and `–`.

**Comment by johnz1** [comment] 2017-03-16 17:54
Yes indeed.  Thank you very much

**Comment by shlomi-noach** [comment] 2017-03-27 05:35
Addressed by https://github.com/github/gh-ost/pull/389

**Comment by shlomi-noach** [comment] 2017-03-29 06:00
fixed by https://github.com/github/gh-ost/pull/389 (no release yet)

**Closed by shlomi-noach** 2017-03-29 06:00 UTC
