### ISSUE TITLE
Gh-ost with sql_log_bin false

### ISSUE THREAD

**Issue by mayanksamrat** [github/gh-ost#354] opened 2017-01-09 10:07 UTC
Is there any option we can alter our db with sql_log_bin false option. I don't want this change to be replicate on slave.

**Comment by mayanksamrat** [comment] 2017-01-09 10:14
Is there any option we can alter our db with sql_log_bin false option. I don't want this change to be replicate on slave.

**Comment by shlomi-noach** [comment] 2017-01-09 10:30
duplicate of https://github.com/github/gh-ost/issues/149

short answer: we don't have plans to implement it in the near future.

**Closed by shlomi-noach** 2017-01-09 10:30 UTC
