### ISSUE TITLE
Wrong build for x86_64 for 1.1.4 and 1.1.3

### ISSUE THREAD

**Issue by kedarvj** [github/gh-ost#1099] opened 2022-02-25 13:51 UTC
Looks like wrong build for 1.1.4 and 1.1.3:
```
[root@centos_3 ~]# rpm -ivh gh-ost-1.1.4-1.x86_64.rpm
Preparing...                          ################################# [100%]
	package gh-ost-1:1.1.4-1.x86_64 is intended for a different operating system
[root@centos_3 ~]# rpm -q --qf "%{OS}\n" -p  gh-ost-1.1.4-1.x86_64.rpm
darwin
[root@centos_3 ~]# uname -a
Linux centos_3.localdomain 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@centos_3 ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```

But 1.1.2 works well:
```
[root@centos_3 ~]# rpm -ivh gh-ost-1.1.2-1.x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:gh-ost-1:1.1.2-1                 ################################# [100%]
[root@centos_3 ~]# rpm -q --qf "%{OS}\n" -p  gh-ost-1.1.2-1.x86_64.rpm
linux
[root@centos_3 ~]#```

**Comment by dm-2** [comment] 2022-02-25 14:39
Thanks @kedarvj, I can confirm this - the problem was due to a change in build environment.

I've fixed the build script here:
- https://github.com/github/gh-ost/pull/1100

And updated the existing releases:
- [v1.1.3](https://github.com/github/gh-ost/releases/tag/v1.1.3)
- [v1.1.4](https://github.com/github/gh-ost/releases/tag/v1.1.4)

I've close this issue as resolved, feel free to re-open if needed!

**Closed by dm-2** 2022-02-25 14:39 UTC
Labels: bug, build
