### ISSUE TITLE
Deadlock found and gh-ost terminates

### ISSUE THREAD

**Issue by jessicalu2016** [github/gh-ost#635] opened 2018-09-06 19:11 UTC
Hi guys,

We got  following error.  Is there a way gh-ost can retry rather than fail?

------------------------------------------------------------------------------------------------------
Copy: 146866200/155038476 94.7%; Applied: 6181442; Backlog: 13/1000; Time: 21h49m0s(total), 21h48m56s(copy); streamer: mysql-bin-changelog.061867:95542167; State: migrating; ETA: 1h12m50s
2018-09-06 16:49:50 ERROR Error 1213: Deadlock found when trying to get lock; try restarting transaction
2018-09-06 16:49:50 INFO Row copy complete
2018-09-06 16:49:50 FATAL Error 1213: Deadlock found when trying to get lock; try restarting transaction

Thank you!

**Comment by zmoazeni** [comment] 2018-09-06 20:16
Do you know what you're doing that is causing the deadlock? It won't just be gh-ost. Another connection should be applying for locks within a transaction.

If you're running InnoDB you can try running `show engine innodb status` and it will give you information on the two connection queries that collided.

**Comment by jessicalu2016** [comment] 2018-09-06 20:29
yeah, we have another process batch update the table as well. but we are just curious if gh-ost have some sort of retry mechanism? seems it give up immediately

**Comment by shlomi-noach** [comment] 2018-09-07 04:38
Could you please run again, with `--debug --stack`?
`gh-ost` has plenty of retries, I'm curious what fails here and I don't have enough context from the logs.

**Comment by jessicalu2016** [comment] 2018-09-12 13:30
Hi @shlomi-noach, I ran again with the same table and it succeeded. but we got this error again with another table, see stacktrace below. any ideas?

`2018-09-12 13:18:21 DEBUG ApplyDMLEventQueries() applied 10 events in one transaction
2018-09-12 13:18:21 DEBUG ApplyDMLEventQueries() applied 8 events in one transaction
2018-09-12 13:18:24 ERROR Error 1213: Deadlock found when trying to get lock; try restarting transaction
goroutine 101 [running]:
runtime/debug.Stack(0x68, 0x100, 0xc42001e1e0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x938b60, 0xc4203e8a00, 0x6d43ec, 0xc4202a1b01)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0xfd
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x938b60, 0xc4203e8a00, 0x429096, 0x7ba008)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x3e
github.com/github/gh-ost/go/logic.(*Migrator).iterateChunks.func1(0x938b60, 0xc4203e8a00, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:1076 +0x64
github.com/github/gh-ost/go/logic.(*Migrator).iterateChunks.func2.1(0xc4200cc580, 0xf4240)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:1121 +0x75
github.com/github/gh-ost/go/logic.(*Migrator).retryOperation(0xc42010e090, 0xc4200f35a0, 0x0, 0x0, 0x0, 0x5b99121d, 0xc420409f38)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:140 +0x75
github.com/github/gh-ost/go/logic.(*Migrator).iterateChunks.func2(0xbede62675ddd2d14, 0x9e1dfc52cf16)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:1127 +0xe0
github.com/github/gh-ost/go/logic.(*Migrator).executeWriteFuncs(0xc42010e090, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:1220 +0x195
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:387 +0x66f
2018-09-12 13:18:24 INFO Row copy complete
2018-09-12 13:18:24 FATAL Error 1213: Deadlock found when trying to get lock; try restarting transaction
goroutine 8 [running]:
runtime/debug.Stack(0x68, 0x100, 0xc420764050)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x0, 0x938b60, 0xc4203e8a00, 0x1, 0x101)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0xfd
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Fatale(0x938b60, 0xc4203e8a00, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:255 +0x3e
github.com/github/gh-ost/go/logic.(*Migrator).listenOnPanicAbort(0xc42010e090)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:252 +0x6a
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:319 +0x26e`

**Comment by jessicalu2016** [comment] 2018-09-17 13:16
Hi @shlomi-noach, does the above stacktrace provide you some context?

**Comment by shlomi-noach** [comment] 2018-09-18 06:10
The problem is identified. You are correct @jessicalu2016 that `gh-ost` bails out without retrying.
The problem is with `terminateRowIteration` from within `applyCopyRowsFunc()` as in 
https://github.com/github/gh-ost/blob/17b170dd1fcace81e2be75e5b749791d3ac8d03c/go/logic/migrator.go#L1131

This is unneeded and we should only `return err`, because the entire `applyCopyRowsFunc()` is wrapped in a retry mechanism: https://github.com/github/gh-ost/blob/17b170dd1fcace81e2be75e5b749791d3ac8d03c/go/logic/migrator.go#L1137-L1139

I also see this could use a retry, though here it's a slightly more complicated scenario:

https://github.com/github/gh-ost/blob/17b170dd1fcace81e2be75e5b749791d3ac8d03c/go/logic/migrator.go#L1110

**Comment by jessicalu2016** [comment] 2018-09-18 13:29
@shlomi-noach Thanks for looking into this! So I could do following for line 1131 and rebuild gh-ost, right? 
```
          if err != nil {
		return err
	 }
```

And it seems gh-ost will retry 60 times? and I should be able to set it initially in ghost command parameter and update it like this (echo default-retries=100 | nc -U <.sock file>) on the fly? 

Plus, for terminateRowIteration(err) on line 1110, what could cause err? are you planning to fix it in future releases?

**Comment by shlomi-noach** [comment] 2018-09-20 05:51
@jessicalu2016 I intend to fix this. The answer is "yes" to line 1131, and you can try it out. It's just that there's more to handle, in 1110

**Comment by jessicalu2016** [comment] 2018-09-21 14:10
@shlomi-noach ok. I've patched and rebuild the source. I will just it until you guys have a release. Thanks!

**Comment by shlomi-noach** [comment] 2018-09-23 17:51
Addressed by https://github.com/github/gh-ost/pull/644

**Closed** 2018-10-02 05:12 UTC
Labels: bug
